# -*- coding: utf-8 -*-
"""DictionaryQuiz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lpXN0ib1xHicp1KOXF-uGribj6b1-XJX
"""

#   Created by Elshad Karimov on 26/04/2020.
#   Copyright © 2020 AppMillers. All rights reserved

# Dictionary Interview Questions

# Q-1. What will be the output of the following code snippet?
# Answer:  B.  1

a = {(1,2):1,(2,3):2}
print(a[1,2])

# Q-2. What will be the output of the following code snippet?
# Answer: A. Key Error

a = {'a':1,'b':2,'c':3}
print (a['a','b'])

# Q-3. What will be the output of the following code block?
# Answer:  C. 3

fruit = {}

def addone(index):
    if index in fruit:
        fruit[index] += 1
    else:
        fruit[index] = 1
        
addone('Apple')
addone('Banana')
addone('apple')
print (len(fruit))

# Q-4. What will be the output of the following code block?
# Answer:  D. 4

arr = {}
arr[1] = 1
arr['1'] = 2
arr[1] += 1

sum = 0
for k in arr:
    sum += arr[k]

print(sum)

# Q-5. What will be the output of the following code snippet?
# Answer: D. 6

my_dict = {}
my_dict[1] = 1
my_dict['1'] = 2
my_dict[1.0] = 4

sum = 0
for k in my_dict:
    sum += my_dict[k]
    
print (sum)

# Q-6. What will be the output of the following code snippet?
# Answer: # B. 30   
#        {(1, 2, 4): 8, (4, 2, 1): 10, (1, 2): 12}

my_dict = {}
my_dict[(1,2,4)] = 8
my_dict[(4,2,1)] = 10
my_dict[(1,2)] = 12

sum = 0
for k in my_dict:
    sum += my_dict[k]

print (sum)
print(my_dict)

# Q-7. What will be the output of the following code snippet?
# Answer: D. Type Error

box = {}
jars = {}
crates = {}
box['biscuit'] = 1
box['cake'] = 3
jars['jam'] = 4
crates['box'] = box
crates['jars'] = jars
print(len(crates[box]))

# Q-8. What will be the output of the following code block?
# Answer: A. 96 98 97

dict = {'c': 97, 'a': 96, 'b': 98}

for _ in sorted(dict):
    print (dict[_])

# Q-9. What will be the output of the following code snippet?
# Answer: B. False

rec = {"Name" : "Python", "Age":"20"}
r = rec.copy()
print(id(r) == id(rec))

# Q-10. What will be the output of the following code snippet?
# Answer: B. False
rec = {"Name" : "Python", "Age":"20", "Addr" : "NJ", "Country" : "USA"}
id1 = id(rec)
del rec
rec = {"Name" : "Python", "Age":"20", "Addr" : "NJ", "Country" : "USA"}
id2 = id(rec)
print(id1 == id2)